server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # ??? ?? ? ?? DB? ?? ???? ??
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql # DB ?? ??
  servlet:
    multipart:
      max-file-size: 10MB # 1개의 파일의 최대 사이즈
      max-request-size: 20MB # 전체 요청의 최대 사이즈


logging.level:
  org.hibernate.SQL: debug

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html

jwt:
  secret: PiVD/O4Zn94PmX47y0sCKKd+I1ttMrKOOfbIT9nud/0T9RowC2TUkzqC4xV68rwfY9/IYn7484Do3NPxMeHwHA==

# 업로드 파일 저장 경로
upload:
  path: c:/todo_upload